# Generated by Django 4.2.16 on 2024-11-13 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_control_name_alter_domain_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subdomain',
            old_name='description',
            new_name='objective',
        ),
    ]
