# Generated by Django 4.2.16 on 2024-11-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_description_subdomain_objective'),
    ]

    operations = [
        migrations.RenameField(
            model_name='control',
            old_name='name',
            new_name='code',
        ),
    ]
