# Generated by Django 4.2.16 on 2024-11-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectcontrol_auditor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='metadata',
        ),
    ]
