# Generated by Django 4.2.16 on 2024-11-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Used', 'Used')], default='Pending', max_length=10),
        ),
    ]
